# Data parameters
data_source: fx
add_cash_asset: True
start_date: 1/1/2015
num_asset: 7
num_data: 6400
window_length: 64
ohlc_interval: 1h
path: data/fx_data
file_extension: .csv

# TA-LIB
indicators:
#    - god_price
#    - god_return
#    - god_future_dir
    - log_return
    - above_mean
    - norm_price
    - mov_avg_5
    - rsi
    - macd_hist
    - stochastic
    - stochRSI
    - spinning_top
    - hikkake

# Environment parameters
env: FX
trading_cost: 0.0 # 0.0005
time_cost: 0
n_features: 10
state_dim: 24 # state_dim PER asset, i.e. input state_dim = n_features * num_asset * state_dim
action_dim: 1 # action_dim PER asset, i.e. output action_dim = num_asset * action_dim
action_low: -1
action_high: 1
num_agents: 2
random_seed: 1983

# Training parameters
model: ddpg
batch_size: 256
num_steps_train: 100_000 # number of episodes from all agents
max_ep_length: 480 # maximum number of steps per episode
replay_mem_size: 1_000_000 # maximum capacity of replay memory
discount_rate: 0.99 # Discount rate (gamma) for future rewards
n_step_returns: 1 # number of future steps to collect experiences for N-step returns
update_agent_ep: 1 # agent gets latest parameters from learner every update_agent_ep episodes
replay_queue_size: 64 # queue with replays from all the agents
batch_queue_size: 64 # queue with batches given to learner
num_episode_save: 20
device: cuda
agent_device: cpu
save_reward_threshold: 0.01 # difference in best reward to save agent model

# Network parameters
critic_learning_rate: 0.0005
actor_learning_rate: 0.0005
dense_size: 400 # size of the 2 hidden layers in networks
final_layer_init: 0.003
tau: 0.001 # parameter for soft target network updates

# Miscellaneous
results_path: results
n_threads: 4 # Total number of child threads